# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9a6784dde15ce22de947917b81f5987882dc3178964a8ab94e2a7d5013d894918282f8a17183f5eb515d81dcbf79f31be81b8939d50b29280637dd481c50a0

test:
  secret_key_base: 9ae99d486a35213453f84b9ab79e8f946bf438cd2155bd43da82c17c39e01d43fac5c59de1463de2873bddbe725c5b026c8c5dca9505422d336146ad736cc713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_auth:
    name: admin
    password: password
  managers_emails: email
  gdrive:
    auth:
      user: user
      password: password
  sms:
    key: key
    private_key: private_key

beta:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  http_auth:
    name: admin
    password: password
  managers_emails: email
  gdrive:
    auth:
      user: user
      password: password
  sms:
    key: key
    private_key: private_key
