seo:
  product_title: "- %s купить в Днепропетровске, Киеве, Харькове, Одессе, Симферополе, Донецке, в Украине"
  product_description: "выгодная цена в интернет-магазине Babysmile: Днепропетровск, Киев, Харьков, Одесса, Симферополь, Донецк. Новинки, лучшие цены, доставка по Украине, гарантия производителя"
  category_title: "- купить по низкой цене в Днепропетровске, Киеве, Харькове, Одессе, Симферополе, Донецке, в Украине"
  category_description: "выгодная цена в интернет-магазине Babysmile: Днепропетровск, Киев, Харьков, Одесса, Симферополь, Донецк. Новинки, лучшие цены, доставка по Украине, гарантия производителя"
