seo:
  product_title: "- %s купить в Украине"
  product_description: "доставка по Украине"
  category_title: "- купить в Украине"
  category_description: "доставка по Украине"
misc:
  search_suggestions: "коляска трость, автокресло группа 0, кроватки верес, everflo, для новорожденных, для девочек, игрушка для мальчика, игрушки для малышей, ходунки mioo, видеоняня, радионяня, стульчики для кормления, prima pappa, подвески на кроватку, прогулочные коляски, нарядный костюм мальчику, лыжи, санки, ледянка, disney, велосипед, безопасность малыша, увлажнитель воздуха, постель, для двойни, ящик для игрушек"
