seo:
  products_title: "купить в Днепропетровске, Киеве, Харькове, Одессе, Симферополе, Донецке, в Украине"
  products_description: "в интернет-магазине Babysmile: Днепропетровск, Киев, Харьков, Одесса, Симферополь, Донецк. Новинки, лучшие цены, доставка по Украине, гарантия производителя"
