seo:
  defaults:
    description: "Интернет-магазин детских товаров Babysmile: детские коляски, детская мебель, игрушки для детей, автокресла, детская гигиена. Доставка по Украине"
    keywords: [Babysmile, интернет-магазин, детский, купить, малыши]
misc:
  search_suggestions: "коляска трость, автокресло группа 0, кроватки верес, everflo, для новорожденных, для девочек, игрушка для мальчика, игрушки для малышей, ходунки mioo, видеоняня, радионяня, стульчики для кормления, prima pappa, подвески на кроватку, прогулочные коляски, нарядный костюм мальчику, лыжи, санки, ледянка, disney, велосипед, безопасность малыша, увлажнитель воздуха, постель, для двойни, ящик для игрушек"
