language: ru
toolbar:
  - styleselect | bold italic | link unlink image pastetext | undo redo | bullist numlist outdent indent | alignleft aligncenter alignright alignjustify | table youtube
menubar: false
plugins:
  - link
  - table
  - code
  - image
  - paste
  - youtube
height: 300
relative_urls: false
convert_urls: false
document_base_url: '/'
remove_script_host: true
