managers_emails: <%= Rails.application.secrets.managers_emails %>
ga:
  tracking_id: UA-42471160-2
metrika:
  tracking_id: 22781617
  webvisor_enabled: false
gdrive:
  docs:
    prices: 0Aswwzh8AZzVydEl6QkVyeFYzRWFLODhiYlV1T2w3SHc
    products: 0Aswwzh8AZzVydFdLOENUNzk5Q1ZCVV9ibXlublpQZXc
sms:
  test_mode: false
liqpay:
  sandbox: true
