managers_emails: test@localhost
ga:
  tracking_id: 'fake-id'
metrika:
  tracking_id: 'fake-id'
  webvisor_enabled: false
gdrive:
  auth:
    user: user
    password: pass
  docs:
    prices: doc-key
sms:
  test_mode: true
liqpay:
  sandbox: true
